### ISSUE TITLE
vs2019 Unable to install

### ISSUE THREAD

**Issue by FynnFbc** [sergiye/hiberbeeTheme#1]
This is the vs version I installed.
![image](https://github.com/sergiye/hiberbeeTheme/assets/32776949/64522744-b2c7-4024-9e89-319593d56ccb)
Please modify it for compatibility as soon as possible.
Thanks

**Comment by FynnFbc** [comment]
Installation prompt requires CoreEdit component

**Comment by FynnFbc** [comment]
![image](https://github.com/sergiye/hiberbeeTheme/assets/32776949/edb1793c-b1ac-46a2-9d27-9272820fa687)

**Comment by sergiye** [comment]
thanks for feedback, 
installed vs2019 & vs2017 to check compatibility and fixed installation issue, 

<img width="326" alt="install" src="https://github.com/sergiye/hiberbeeTheme/assets/4639111/8de78a2b-9343-4c93-b2c9-61e34e045a49">

but I have to admit that older versions of vs do not have full color scheme customization support in the IDE, so I advise you to upgrade to vs2022.
