### ISSUE TITLE
Some keywords are not displayed clearly

### ISSUE THREAD

**Issue by FynnFbc** [sergiye/hiberbeeTheme#2]
Some keywords are not displayed clearly and cannot be seen
![image](https://github.com/sergiye/hiberbeeTheme/assets/32776949/55648c18-2a5d-474c-baba-8341da70a58b)

**Comment by FynnFbc** [comment]
vs2019

**Comment by sergiye** [comment]
hi, can you try to open same code in vs2022?

**Comment by FynnFbc** [comment]
I have not installed vs2022 and cannot test

**Comment by sergiye** [comment]
as i mentioned here #1 old versions of vs do not have full color scheme customization support

**Comment by sergiye** [comment]
example in vs2022
<img width="594" alt="code" src="https://github.com/sergiye/hiberbeeTheme/assets/4639111/d668671b-f043-45c7-a016-f88da4aa930b">

**Comment by FynnFbc** [comment]
Well, it looks like I only have to upgrade vs.
