### ISSUE TITLE
Sticky Scroll background color

### ISSUE THREAD

**Issue by TylerHoerschgen98** [sergiye/hiberbeeTheme#3]
I'm a big fan of this theme, but I have noticed an unappealing background color when I enable the 'sticky scroll' feature in VS (Options -> Text Editor). The 'stuck' lines of text have an unappealing yellow background color. I think a darker color would be more visually appealing.

![image](https://github.com/sergiye/hiberbeeTheme/assets/131504070/5335da53-96e2-41cb-b456-1014bf690aa1)

**Comment by sergiye** [comment]
problem solved, thanks for the report
